######################################################################
# Automatically generated by qmake (1.07a) Thu Jun 16 17:07:54 2005
######################################################################

TEMPLATE = subdirs

!isEmpty(QTROOTSYSDIR) {
  DESTDIR=$$QTROOTSYSDIR
}
isEmpty(DESTDIR) {
  DESTDIR=..
}
QTROOTSYSDIR=$$DESTDIR

SUBDIRS = qglviewer/QGLViewer qtgl
IVROOT = $$IVROOT
!isEmpty(IVROOT) 
{
   exists($(IVROOT)/include/Inventor)  SUBDIRS+=qtcoin
}
