######################################################################
# Automatically generated by qmake (2.00a) Fri Jul 15 16:23:12 2005
######################################################################

TEMPLATE = app thread
win32: CONFIG += console
DEPENDPATH += .
INCLUDEPATH += .

# Input
TARGET = HelloZoomer
HEADERS += PixmapWidget.h
SOURCES += main.cxx PixmapWidget.cxx
